[package]
name = "piltover"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
openzeppelin = "0.20.0"

[dev-dependencies]
starknet = "2.9.2"
snforge_std = "0.34.0"
openzeppelin_testing = "0.20.0"

[scripts]
test = "snforge test"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true

[features]
messaging_test = []
